// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Footer → Selos*
 */
export interface FooterDocumentDataSelosItem {
  /**
   * Selo field in *Footer → Selos*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.selos[].selo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  selo: prismic.ImageField<never>;
}

/**
 * Item in *Footer → Social Media*
 */
export interface FooterDocumentDataSocialMediaItem {
  /**
   * Ícone social field in *Footer → Social Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[].social_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  social_icon: prismic.ImageField<never>;

  /**
   * Link social field in *Footer → Social Media*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Ex: https://www.instagram.com/alexandria.energia/
   * - **API ID Path**: footer.social_media[].social_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Footer → Links Externos*
 */
export interface FooterDocumentDataLinksExternosItem {
  /**
   * Link field in *Footer → Links Externos*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Ex: Politicas de privacidade
   * - **API ID Path**: footer.links_externos[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Imagem de background field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.background_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Logo field in *Footer*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Selos field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.selos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  selos: prismic.GroupField<Simplify<FooterDocumentDataSelosItem>>;

  /**
   * Titulo endereço field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Endereço
   * - **API ID Path**: footer.title_address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_address: prismic.RichTextField;

  /**
   * Endereço field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: R. Fernando Amaro, 60 - Alto da XV, Curitiba - PR, 80045-080
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address: prismic.RichTextField;

  /**
   * Titulo Social Media field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Siga a Alexandria nas redes sociais
   * - **API ID Path**: footer.social_media_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  social_media_title: prismic.RichTextField;

  /**
   * Social Media field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.social_media[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_media: prismic.GroupField<Simplify<FooterDocumentDataSocialMediaItem>>;

  /**
   * Texto de Copyright field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: © 2025 Alexandria. Todos os direitos reservados.
   * - **API ID Path**: footer.copyright_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copyright_text: prismic.RichTextField;

  /**
   * Links Externos field in *Footer*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.links_externos[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links_externos: prismic.GroupField<
    Simplify<FooterDocumentDataLinksExternosItem>
  >;

  /**
   * Numero de suporte  field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: numero do WhtasApp
   * - **API ID Path**: footer.support_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  support_number: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

/**
 * Item in *Header  → Menu de Navegaçao*
 */
export interface HeaderDocumentDataNavMenuItem {
  /**
   * Item do menu field in *Header  → Menu de Navegaçao*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Ínicio
   * - **API ID Path**: header.nav_menu[].menu_item
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  menu_item: prismic.RichTextField;

  /**
   * Ancora field in *Header  → Menu de Navegaçao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: #inicio
   * - **API ID Path**: header.nav_menu[].menu_anchor
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  menu_anchor: prismic.KeyTextField;
}

/**
 * Content for Header  documents
 */
interface HeaderDocumentData {
  /**
   * Logo field in *Header *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Menu de Navegaçao field in *Header *
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.nav_menu[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  nav_menu: prismic.GroupField<Simplify<HeaderDocumentDataNavMenuItem>>;

  /**
   * CTA field in *Header *
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: Portal do cliente
   * - **API ID Path**: header.cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta: prismic.KeyTextField;

  /**
   * Link do CTA field in *Header *
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: www.google.com
   * - **API ID Path**: header.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_link: prismic.KeyTextField;
}

/**
 * Header  document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | QrCodeSlice
  | CarrosselSlice
  | VideoSlice
  | MockupSlice
  | CtaSectionSlice
  | EcossistemaSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes =
  | FooterDocument
  | HeaderDocument
  | HomepageDocument;

/**
 * Item in *Carrossel → Default → Primary → Carrossel*
 */
export interface CarrosselSliceDefaultPrimaryCarouselItem {
  /**
   * Imagem field in *Carrossel → Default → Primary → Carrossel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.default.primary.carousel[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Título do card field in *Carrossel → Default → Primary → Carrossel*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Somos matchmaking
   * - **API ID Path**: carrossel.default.primary.carousel[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_title: prismic.RichTextField;

  /**
   * Texto do card field in *Carrossel → Default → Primary → Carrossel*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Texto descritivo do card
   * - **API ID Path**: carrossel.default.primary.carousel[].card_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_text: prismic.RichTextField;
}

/**
 * Primary content in *Carrossel → Default → Primary*
 */
export interface CarrosselSliceDefaultPrimary {
  /**
   * Título field in *Carrossel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: A Lex não é apenas energia por assinatura
   * - **API ID Path**: carrossel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Carrossel field in *Carrossel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carrossel.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  carousel: prismic.GroupField<
    Simplify<CarrosselSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for Carrossel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarrosselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarrosselSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Carrossel*
 */
type CarrosselSliceVariation = CarrosselSliceDefault;

/**
 * Carrossel Shared Slice
 *
 * - **API ID**: `carrossel`
 * - **Description**: Carrossel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarrosselSlice = prismic.SharedSlice<
  "carrossel",
  CarrosselSliceVariation
>;

/**
 * Item in *CtaCards → Default → Primary → Cards*
 */
export interface CtaSectionSliceDefaultPrimaryCardsItem {
  /**
   * Imagem do card field in *CtaCards → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.cards[].card_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Titulo do card field in *CtaCards → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Seja um Líder Lex
   * - **API ID Path**: cta_section.default.primary.cards[].card_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_title: prismic.RichTextField;

  /**
   * Descrição do card field in *CtaCards → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto decritivo do card
   * - **API ID Path**: cta_section.default.primary.cards[].card_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  card_description: prismic.RichTextField;

  /**
   * Texto CTA field in *CtaCards → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: Quero ser um Cliente Lex
   * - **API ID Path**: cta_section.default.primary.cards[].cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * Link CTA field in *CtaCards → Default → Primary → Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Ex: www.google.com
   * - **API ID Path**: cta_section.default.primary.cards[].cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *CtaCards → Default → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
  /**
   * Imagem de background field in *CtaCards → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Título field in *CtaCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Aqui, a escolha é sua
   * - **API ID Path**: cta_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Cards field in *CtaCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<CtaSectionSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for CtaCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaCards*
 */
type CtaSectionSliceVariation = CtaSectionSliceDefault;

/**
 * CtaCards Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CtaSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSlice = prismic.SharedSlice<
  "cta_section",
  CtaSectionSliceVariation
>;

/**
 * Primary content in *Gradient → Default → Primary*
 */
export interface EcossistemaSliceDefaultPrimary {
  /**
   * Imagem de background field in *Gradient → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ecossistema.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Imagem field in *Gradient → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ecossistema.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titulo field in *Gradient → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: A Lex é um ecossistema.
   * - **API ID Path**: ecossistema.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *Gradient → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto descritivo da seção
   * - **API ID Path**: ecossistema.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Gradient Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EcossistemaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EcossistemaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Gradient → Secondary → Primary*
 */
export interface EcossistemaSliceSecondaryPrimary {
  /**
   * Imagem de background field in *Gradient → Secondary → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ecossistema.secondary.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Imagem field in *Gradient → Secondary → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: ecossistema.secondary.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Titulo field in *Gradient → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: A Lex é um ecossistema.
   * - **API ID Path**: ecossistema.secondary.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Texto field in *Gradient → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Texto descritivo da seção
   * - **API ID Path**: ecossistema.secondary.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Secondary variation for Gradient Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EcossistemaSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<EcossistemaSliceSecondaryPrimary>,
  never
>;

/**
 * Slice variation for *Gradient*
 */
type EcossistemaSliceVariation =
  | EcossistemaSliceDefault
  | EcossistemaSliceSecondary;

/**
 * Gradient Shared Slice
 *
 * - **API ID**: `ecossistema`
 * - **Description**: Ecossistema
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EcossistemaSlice = prismic.SharedSlice<
  "ecossistema",
  EcossistemaSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Imagem de fundo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Imagem de complemento field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.addon_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  addon_image: prismic.ImageField<never>;

  /**
   * Imagem principal field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image_principal
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_principal: prismic.ImageField<never>;

  /**
   * Título field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Título principal da seção
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtítulo field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Subtítulo da seçao
   * - **API ID Path**: hero.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Mockup → Default → Primary*
 */
export interface MockupSliceDefaultPrimary {
  /**
   * Imagem de background field in *Mockup → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mockup.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Imagem field in *Mockup → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mockup.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Título field in *Mockup → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Não vendemos energia.
   * - **API ID Path**: mockup.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Imagem gradiente para a descrição field in *Mockup → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: mockup.default.primary.gradient_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  gradient_image: prismic.ImageField<never>;

  /**
   * Descrição field in *Mockup → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Texto descritivo do que se trata a seção
   * - **API ID Path**: mockup.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Texto field in *Mockup → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Textos separado por quebra de linhas
   * - **API ID Path**: mockup.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for Mockup Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MockupSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MockupSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Mockup*
 */
type MockupSliceVariation = MockupSliceDefault;

/**
 * Mockup Shared Slice
 *
 * - **API ID**: `mockup`
 * - **Description**: Mockup
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MockupSlice = prismic.SharedSlice<"mockup", MockupSliceVariation>;

/**
 * Item in *QrCode → Default → Primary → Códigos QR*
 */
export interface QrCodeSliceDefaultPrimaryQrCodesItem {
  /**
   * Título field in *QrCode → Default → Primary → Códigos QR*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Baixe nosso app
   * - **API ID Path**: qr_code.default.primary.qr_codes[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * App Store field in *QrCode → Default → Primary → Códigos QR*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: qr_code.default.primary.qr_codes[].app_store
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  app_store: prismic.ImageField<never>;

  /**
   * PlayStore field in *QrCode → Default → Primary → Códigos QR*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: qr_code.default.primary.qr_codes[].playstore
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  playstore: prismic.ImageField<never>;

  /**
   * Qr Code field in *QrCode → Default → Primary → Códigos QR*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: qr_code.default.primary.qr_codes[].qr_code
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  qr_code: prismic.ImageField<never>;
}

/**
 * Primary content in *QrCode → Default → Primary*
 */
export interface QrCodeSliceDefaultPrimary {
  /**
   * Imagem de background field in *QrCode → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: qr_code.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Titulo field in *QrCode → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Baixe o aplicativo
   * - **API ID Path**: qr_code.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *QrCode → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Disponível para iOS e Android.
   * - **API ID Path**: qr_code.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Códigos QR field in *QrCode → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: qr_code.default.primary.qr_codes[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  qr_codes: prismic.GroupField<Simplify<QrCodeSliceDefaultPrimaryQrCodesItem>>;
}

/**
 * Default variation for QrCode Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QrCodeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QrCodeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QrCode*
 */
type QrCodeSliceVariation = QrCodeSliceDefault;

/**
 * QrCode Shared Slice
 *
 * - **API ID**: `qr_code`
 * - **Description**: QrCode
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type QrCodeSlice = prismic.SharedSlice<"qr_code", QrCodeSliceVariation>;

/**
 * Primary content in *Video → Default → Primary*
 */
export interface VideoSliceDefaultPrimary {
  /**
   * Video field in *Video → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: video.default.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Título field in *Video → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Conheça o Grupo por trás das engrenagens da Lex
   * - **API ID Path**: video.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Descrição field in *Video → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Ex: Somos apaixonados em resolver o difícil para você não precisar.
   * - **API ID Path**: video.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Texto do CTA field in *Video → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ex: Conheça o time Alexandria
   * - **API ID Path**: video.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * Link do CTA field in *Video → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: ex: www.google.com
   * - **API ID Path**: video.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Video Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Video*
 */
type VideoSliceVariation = VideoSliceDefault;

/**
 * Video Shared Slice
 *
 * - **API ID**: `video`
 * - **Description**: Video
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoSlice = prismic.SharedSlice<"video", VideoSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      FooterDocument,
      FooterDocumentData,
      FooterDocumentDataSelosItem,
      FooterDocumentDataSocialMediaItem,
      FooterDocumentDataLinksExternosItem,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataNavMenuItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CarrosselSlice,
      CarrosselSliceDefaultPrimaryCarouselItem,
      CarrosselSliceDefaultPrimary,
      CarrosselSliceVariation,
      CarrosselSliceDefault,
      CtaSectionSlice,
      CtaSectionSliceDefaultPrimaryCardsItem,
      CtaSectionSliceDefaultPrimary,
      CtaSectionSliceVariation,
      CtaSectionSliceDefault,
      EcossistemaSlice,
      EcossistemaSliceDefaultPrimary,
      EcossistemaSliceSecondaryPrimary,
      EcossistemaSliceVariation,
      EcossistemaSliceDefault,
      EcossistemaSliceSecondary,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      MockupSlice,
      MockupSliceDefaultPrimary,
      MockupSliceVariation,
      MockupSliceDefault,
      QrCodeSlice,
      QrCodeSliceDefaultPrimaryQrCodesItem,
      QrCodeSliceDefaultPrimary,
      QrCodeSliceVariation,
      QrCodeSliceDefault,
      VideoSlice,
      VideoSliceDefaultPrimary,
      VideoSliceVariation,
      VideoSliceDefault,
    };
  }
}
