// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  carrossel: dynamic(() => import("./Carrossel")),
  cta_section: dynamic(() => import("./CtaCards")),
  ecossistema: dynamic(() => import("./Gradient")),
  hero: dynamic(() => import("./Hero")),
  mockup: dynamic(() => import("./Mockup")),
  qr_code: dynamic(() => import("./QrCode")),
  video: dynamic(() => import("./Video")),
};
